#ifndef VELK_RENDER_INTF_MATERIAL_H
#define VELK_RENDER_INTF_MATERIAL_H

#include <velk/string_view.h>
#include <velk/vector.h>

#include <velk-render/interface/intf_program.h>

namespace velk {

class IRenderContext;
class ISurface;

/**
 * @brief Renderable material.
 *
 * Every material provides one shading body — a GLSL function
 * `velk_eval_<name>(EvalContext) -> MaterialEval` — plus a vertex
 * shader that emits the canonical set of varyings. Path-specific
 * drivers (forward fragment / deferred fragment / RT fill) are
 * generated by the renderer from this single eval function, so adding
 * a render path to the framework doesn't require touching any
 * material.
 *
 * Chain: IInterface -> IGpuResource -> IProgram -> IMaterial
 */
class IMaterial : public Interface<IMaterial, IProgram>
{
public:
    /// GLSL source defining `MaterialEval <fn_name>(EvalContext ctx)`.
    virtual string_view get_eval_src() const = 0;

    /// Name of the eval function defined in @ref get_eval_src.
    virtual string_view get_eval_fn_name() const = 0;

    /// Vertex shader source for this material. For now each material
    /// supplies its own (instance layout differs); a later slice will
    /// factor common cases into reusable prefabs.
    virtual string_view get_vertex_src() const = 0;

    /// Full fragment shader source. Non-empty iff this material bypasses
    /// the eval-driver composition (e.g. ShaderMaterial, which lets the
    /// user supply a complete fragment). Default is empty; eval-based
    /// materials leave this empty and rely on get_eval_src() instead.
    virtual string_view get_fragment_src() const { return {}; }

    /// Opt-in: register any shader includes the eval_src depends on
    /// (e.g. `velk_text.glsl`). Called before the first compile.
    virtual void register_eval_includes(IRenderContext& /*ctx*/) const = 0;

    /// Alpha-discard threshold for the forward fragment driver. Fragments
    /// with `color.a` below the threshold are discarded.
    virtual float get_forward_discard_threshold() const = 0;

    /// Alpha-discard threshold for the deferred fragment driver. Deferred
    /// has no alpha blending, so a higher threshold is the default.
    virtual float get_deferred_discard_threshold() const = 0;

    /// Returns the bindable textures this material samples, in slot order.
    /// The renderer resolves each to a bindless TextureId and writes them
    /// into DrawDataHeader::texture_ids[] in the same order, so shader code
    /// can index them by fixed position. Default: no textures.
    virtual vector<ISurface*> get_textures() const = 0;
};

} // namespace velk

#endif // VELK_RENDER_INTF_MATERIAL_H
